### ISSUE TITLE
"Print" prints normal magento2 invoice

### ISSUE THREAD

**Issue by skymeissner** [EaDesgin/magento2-pdf-generator2#1]
I can successfully intall the module. The db table are there. The admin config is there. But when I click on "print" it creates just the normal magento2 invoice. Any idea?

**Comment by eadesignro** [comment]
Did you try the system/configuration settings to yes??

**Comment by eadesignro** [comment]
Also please check if you have installed the [mpdf](https://github.com/mpdf/mpdf) library. If you do not have that it will output the normal Magento 2 PDF.

**Comment by skymeissner** [comment]
>Did you try the system/configuration settings to yes?? 
Haha. No, I didn't.

I still have some permission issues. I might get back tou if I don't get it going. 
Thanks.

**Comment by skymeissner** [comment]
Needed to give the webserve write perms on vendor/mpdf/mpdf/ttfontdata. It works now, yeah!

**Comment by skymeissner** [comment]
Juast as info. I would get composer to install pdfgenerator first because mageento already had a requirement for mpdf 6.x while pdfgenerator needs 7.x. I forked the project and lowered the pdfgenerator requirement. Seems to work.

**Comment by eadesignro** [comment]
Is ok, but i thing there are PHP 7 issues with older versions. If it works ok let me know.
