### ISSUE TITLE
Not working on magento CE 2.1.7

### ISSUE THREAD

**Issue by blacklizardul** [EaDesgin/magento2-pdf-generator2#11]
Module is activated from stores->configuration,
Template is activated and set as default.
If i try to print the order i get the magento defult template, the invoice is not sent by email.
No errors. Nothing in logs.

Can you help with this issue please?

**Comment by eadesignro** [comment]
Hi, @blacklizardul 

Please add the extension version.

Thansk,

**Comment by blacklizardul** [comment]
Hey ,
Thanks for the fast response.
I am using the version 1.0.29, latest on git.

**Comment by eadesignro** [comment]
Hi, 

We are on vacation until 21 August. We will take a closer look then.

**Comment by eadesignro** [comment]
The module works like it should on a M2.1.8 fresh install. The proper invoice is printed and is attached to the email.
