### ISSUE TITLE
Installed on Magento CE 2.1.7 but not working

### ISSUE THREAD

**Issue by skitter-anton** [EaDesgin/magento2-pdf-generator2#12]
Just installed everything without any problems. 
eadesignro/mpdf
eadesignro/module-eacore
eadesignro/module-pdfgenerator

php magento setup:upgrade;
php magento setup:static-content:deploy
Removed cache

But nothing is visible in backend. Also not in stores>configuration.

**Comment by eadesignro** [comment]
Hi, 

We are on vacation until 21 August. We will take a closer look then.

**Comment by eadesignro** [comment]
The module works like it should on a M2.1.8 fresh install. The proper invoice is printed and is attached to the email.
