### ISSUE TITLE
Magento 2.2 Compatibility

### ISSUE THREAD

**Issue by danslo** [EaDesgin/magento2-pdf-generator2#19]
This module has a hard requirement on version 100.1.* of several Magento modules. Magento 2.2 was released today and it would be nice to have compatibility for this new Magento version.

**Comment by eadesignro** [comment]
@danslo Going to update the composer later. If you have already done this you can PR. 
Thank for pointing this out.

**Comment by danslo** [comment]
I have this installed on a friend's Magento shop, I didn't test it with 2.2 yet (due to this issue), so I can't confirm it works yet. I'll do it in the next few days :+1:

**Comment by eadesignro** [comment]
Ok, Thanks, i will also look at the and of the week or weekend.
Thanks,

**Comment by rishabhchd19** [comment]
Any update for this bug? I am also getting the same problem as not working with 101.* on update Magento 2.2. It was working till 2.1.9

**Comment by danslo** [comment]
Sorry, haven't had time for this yet.

**Comment by eadesignro** [comment]
@danslo I did not have the time, only managed to create a M 2.2.0 project. I will look this afternoon.

**Comment by gewaechshaus** [comment]
@eadesignro - I did install mpdf by composer and put your module incl. all related stuff in the app/code folder... I noticed some errors while compiling and did drop the re-installation as I ran out of time. I didn't analyse them in detail, but it did look like missing includes of some helper data. Just to let you know.

**Comment by eadesignro** [comment]
@gewaechshaus I will look this evening. It should be fast to solve the issues. I know there are some wrong paths.

**Comment by danslo** [comment]
This is one change needed:

https://github.com/danslo/magento2-pdf-generator2/commit/e760bcbb70756629a09ebdcbe5dbb0040d92d60f

I didn't test the extension other than that, but that will fix DI compilation.

**Comment by eadesignro** [comment]
@danslo Yap, that is the one i was aware. :+1:

**Comment by rishabhchd19** [comment]
Also there's an issue in displaying the Order Status. The order status it display as Status Code, not a Status Title. Like, I  changed the status from Default <Processing> to <Processed> but default code doesn't change and remains same as "processing". When an invoice is generated it doesn't Processed but shw processing while the order status shows correct in the admin as Status> Processed.

**Comment by eadesignro** [comment]
@rishabhchd19 Please open a new bug with more detailed explanations. Varible/html code and so on.

**Comment by eadesignro** [comment]
@danslo I made the update. I confirm is working with m 2.2 now. 
I used composer require eadesignro/module-pdfgenerator 1.2.1 because i used an old project updated.
The only thing not working now are unit tests some strange error (can check the travis errors). I did not test in php 7.1. I do not know how mpdf behaves in that php version.

**Comment by eadesignro** [comment]
I will close this bug after i check the unit tests.

**Comment by gewaechshaus** [comment]
Seems to work... Big THX @eadesignro - Will study all related logs tomorow.
