### ISSUE TITLE
Admin Login Error after installing the module

### ISSUE THREAD

**Issue by shazadmaved** [EaDesgin/magento2-pdf-generator2#2]
1 exception(s):
Exception #0 (OutOfRangeException): Specified invalid parent id (Eadesigndev_Eacore::eadesign)

Exception #0 (OutOfRangeException): Specified invalid parent id (Eadesigndev_Eacore::eadesign)
#0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Backend\Model\Menu\Builder->getResult(Object(Magento\Backend\Model\Menu))
#1 /var/www/html/var/generation/Magento/Backend/Model/Menu/Builder/Interceptor.php(39): Magento\Backend\Model\Menu\Builder\Interceptor->___callPlugins('getResult', Array, Array)
#2 /var/www/html/vendor/magento/module-backend/Model/Menu/Config.php(146): Magento\Backend\Model\Menu\Builder\Interceptor->getResult(Object(Magento\Backend\Model\Menu))
#3 /var/www/html/vendor/magento/module-backend/Model/Menu/Config.php(109): Magento\Backend\Model\Menu\Config->_initMenu()
#4 /var/www/html/vendor/magento/module-backend/Model/Url.php(348): Magento\Backend\Model\Menu\Config->getMenu()
#5 /var/www/html/vendor/magento/module-backend/Model/Url.php(308): Magento\Backend\Model\Url->_getMenu()
#6 /var/www/html/vendor/magento/module-backend/Controller/Adminhtml/Index/Index.php(21): Magento\Backend\Model\Url->getStartupPageUrl()
#7 /var/www/html/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(24): Magento\Backend\Controller\Adminhtml\Index\Index->execute()
#8 /var/www/html/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->execute()
#9 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#12 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#13 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#16 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#19 /var/www/html/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#23 /var/www/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#28 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#29 {main}

**Comment by eadesignro** [comment]
Hi,

Try to get a better description of the issue next time.

Try to say "hello", don't just paste your issue;

Try to read the require part of the composer.json.

`"eadesignro/module-eacore": "~0.0.2",
    "eadesignro/mpdf": "~7.0.1"`

**Comment by karthik147** [comment]
HI 
Am having the same issue what is the solution for this.
My Magento 2 version :CE 2.1.7

**Comment by Mahmoud-Refaat** [comment]
Hi 
      still this happening in CE 2.1.9 is there is any update about that issue.

**Comment by Mahmoud-Refaat** [comment]
HI 
    i have solved it by editing etc/adminhml/menu.xml
changing parent="Eadesigndev_Eacore::eadesign"  to parent="Eadesigndev_Pdfgenerator::templates"

**Comment by taqvi** [comment]
Yes It works Mahmoud-Refaat.

**Comment by jbulbule** [comment]
I had the same error and I fixed it by removing the Parent clause and moving the "RomCity" title on the main menu.

Once done, I could reach to successful login and also my link to manage region list also works great. But, when I click on Manage City List I get error as below -

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.eadesign_romcity' doesn't exist, query was: SELECT COUNT(*) FROM `eadesign_romcity` AS `main_table`

What must be wrong? Any suggestion?

**Comment by overtatechdeveloper** [comment]
i am also faceing this error any body have solution then please give me the solution link
thanks

**Comment by Mahmoud-Refaat** [comment]
please try to install the required moudule from this 
eadesignro/module-eacore
link 
https://github.com/EaDesgin/eacore
