### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by ramsystematix** [EaDesgin/magento2-pdf-generator2#20]
Hello I got error after install
Exception #0 (OutOfRangeException): Specified invalid parent id (Eadesigndev_Eacore::eadesign)

**Comment by eadesignro** [comment]
@ramsystematix You did not add the required modules form composer require.

**Comment by ramsystematix** [comment]
during : composer require eadesignro/module-pdfgenerator;
I got below error so i placed manually 

Invalid token provided.
You can also add it manually later by using "composer config github-oauth.github.com <token>"

                                                                                                                                            
  [RuntimeException]                                                                                                                        
  Failed to clone git@github.com:EaDesgin/magento2-pdf-generator2.git, git was not found, check that it is installed and in your PATH env.  
  sh: git: command not found
