### ISSUE TITLE
PHP Errors after migration to Magento 2.2 and PHP7.1

### ISSUE THREAD

**Issue by nobodyMO** [EaDesgin/magento2-pdf-generator2#22]
After the migration to Magento 2.2 and PHP 7.1 I got PHP errors in the mpdf library files.
File  cssmgr.php method MergeCSS tries to set $attr['ID'] for not initialized variables. 
I fixed it locally by changing 
`			if (!isset($attr['ID'])) {
				$attr['ID'] = '';
			}
`

to 

`
                  if (!isset($attr['ID'])) {
			if (!is_array($attr)) {
				$attr=array("ID"=> '');
			} else {
				$attr['ID'] = '';
			}
                  }
`

File  mpdf.php method ConvertSize has an implicit cast  from string to float, witch  results to the following error message:

> Warning: A non-numeric value encountered in /var/www/magento/vendor/eadesignro/mpdf/mpdf.php on line 30648

I fixed it locally by changing 
`
		}} else {
		  	$size *= (25.4 / $this->dpi); //nothing == px
		}

`
to 

`
		} elseif (is_numeric ($size)) {
			$size *= (25.4 / $this->dpi); //nothing == px
		} else {
		  	$size = floatval ($size *(25.4 / $this->dpi); //nothing == px
		}

`
Is it possible to upgrade EaDesgin/mpdf to the current branch of mpdf/mpdf?

**Comment by gewaechshaus** [comment]
Same here!

**Comment by eadesignro** [comment]
@gewaechshaus Hi, we are testing this week on our commercial versions so this will be fixed.

**Comment by gewaechshaus** [comment]
I would also recommend to implement mpdf in the current release direclty through mpdf/mpdf...

**Comment by eadesignro** [comment]
@hmmm whet release are you referring to? did you test another version? It will be best like that.

**Comment by eadesignro** [comment]
@gewaechshaus hmmm whet release are you referring to? did you test another version? It will be best like that.

**Comment by gewaechshaus** [comment]
@eadesignro  - Any news on this?

**Comment by eadesignro** [comment]
@gewaechshaus If time allows it maybe till Monday. Patience.

**Comment by gewaechshaus** [comment]
@eadesignro - thanks for updating us!

**Comment by eadesignro** [comment]
@gewaechshaus This should be ready. Let me know if you find any issue.
