### ISSUE TITLE
Incorrect status of an order in Invoice

### ISSUE THREAD

**Issue by rishabhchd19** [EaDesgin/magento2-pdf-generator2#23]
There's an issue in displaying the Order Status. The order status it displays as `Status Code`, not a `Status Title`. Like, I changed the status from Default to but default code doesn't change and remains same as "processing". When an invoice is generated it doesn't display `Processed` but shows `processing` while the order status shows correct in the Admin as Status> Processed.
![2017-10-13_21-41-16](https://user-images.githubusercontent.com/30948461/31556071-0dbcb116-b061-11e7-97ba-7b8bcbd28d8a.jpg)
![2017-10-13_21-44-25](https://user-images.githubusercontent.com/30948461/31556078-1326aa6c-b061-11e7-8209-394367832f94.jpg)

**Comment by rishabhchd19** [comment]
any update?

**Comment by eadesignro** [comment]
@rishabhchd19 this is a enhancement. It might be done at some point but we cannot say when.

**Comment by rishabhchd19** [comment]
ok..but I will be waiting for it..

**Comment by eadesignro** [comment]
This is not a bug.
