### ISSUE TITLE
Layout XML wrong format or spaces

### ISSUE THREAD

**Issue by tomasvinduska** [EaDesgin/magento2-pdf-generator2#26]
Hello on Magento 2.2 with Magento 2 PDF Invoice Generator 1.2.2
you have something wrong in layout files for me fixed by just reformating them

exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'body': Character content other than whitespace is not allowed because the content type is 'element-only'.
Line: 131

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'body': Character content other than whitespace is not allowed because the content type is 'element-only'.
Line: 131

**Comment by eadesignro** [comment]
Hi,
Please provide details about your working environment. Operation system and so on.

**Comment by eadesignro** [comment]
This is solved.
