### ISSUE TITLE
Print PDF Invoice option not available in front-end.

### ISSUE THREAD

**Issue by wli-dev6** [EaDesgin/magento2-pdf-generator2#32]
Hello Team,

I have installed extension using composer. As per provided front-end invoice download functionality in demo URL: http://demoinv.eadesign.ro, I am not able to see front-end feature.

Also for the backend, only two templates are visible for invoice only.

**Comment by eadesignro** [comment]
Hi,

That is only available on the pro version. Order and so on is only available on the pro only.
