### ISSUE TITLE
Issue after manual installation 

### ISSUE THREAD

**Issue by cristianst** [EaDesgin/magento2-pdf-generator2#33]
After installing the module manually. And after runing `php bin/magento setup:upgrade`
I get the following error.

![image](https://user-images.githubusercontent.com/11995461/33365587-fa5c1628-d4e8-11e7-84a8-d37f93e380d5.png)

Is there any version bug in the last release (1.23) ? I installed the last version from master.

**Comment by eadesignro** [comment]
This does not seem to be related to our module.

**Comment by cristianst** [comment]
Sorry but `Eadesigndev_Pdfgenerator` is not your module? I am having that issue after installing it.

**Comment by cristianst** [comment]
@eadesignro why you close the issue? this is completely related to your module since the error is quite clear. 

`The following modules are outdated : "Eadesigndev_Pdfgenerator data : current version - none, required version - 1.2.3 "`

**Comment by cristianst** [comment]
@eadesignro any input or shall I create the issue again until it gets the necessary attention?

**Comment by eadesignro** [comment]
@cristianst  "necessary attention"?
Maybe you are not aware of how the world works. There will never be necessary attention for users like you. This is a free extension provided as it is. We are offering support on our time as we wish. And you will never get any support. 

You are threaten us with re creating the issue? WOW. This is a public space and i cannot convey to my sincere touts about you and your kind in relation to the lowest forms of life.
