### ISSUE TITLE
di.xml error after upgrading to magento 2.2.1

### ISSUE THREAD

**Issue by Styopchik** [EaDesgin/magento2-pdf-generator2#34]
`Fatal error: Uncaught Magento\Framework\Exception\LocalizedException: Invalid Document Element 'virtualType', attribute 'name': [facet 'pattern'] The value 'Eadesigndev/Pdfgenerator/Model/ResourceModel/Pdfgenerator/Grid/Collection' is not accepted by the pattern '(\\?[a-zA-Z_-ÿ][a-zA-Z0-9_-ÿ]*)(\\[a-zA-Z_-ÿ][a-zA-Z0-9_-ÿ]*)*'. Line: 74 Element 'virtualType', attribute 'name': 'Eadesigndev/Pdfgenerator/Model/ResourceModel/Pdfgenerator/Grid/Collection' is not a valid value of the atomic type 'phpClassName'. Line: 74 Element 'virtualType', attribute 'name': Warning: No precomputed value available, the value was either invalid or something strange happend. Line: 74 in /var/www/html/vendor/magento/framework/Config/Reader/Filesystem.php on line 163`

**Comment by eadesignro** [comment]
Please specify the version of the extension.

**Comment by Styopchik** [comment]
it was eadesignro/module-opicmsppdfgenerator 2.0.6. I've found a solution

**Comment by eadesignro** [comment]
@Styopchik The module is very outdated so if you have a order you should update. If is the case send via email.
