### ISSUE TITLE
Add serveral PDFs to an email

### ISSUE THREAD

**Issue by jwohlfeil** [EaDesgin/magento2-pdf-generator2#36]
Hi,

is there a way to add several pdf documents from different templates to the email? Would be great to add PDFs for license or something similar...

Best regards, Jan

**Comment by eadesignro** [comment]
That is available on the pro version only.

**Comment by jwohlfeil** [comment]
Great, is it https://www.eadesign.ro/magento2/magento2-invoice-credit-memo-shipping-and-product-pdf-generator-pro.html ?

**Comment by eadesignro** [comment]
Yes, but before please move the discussion to email so we keno what the exact specs are.
