### ISSUE TITLE
Extension manager stuck after installing pdf-generator with composer

### ISSUE THREAD

**Issue by neskoc** [EaDesgin/magento2-pdf-generator2#37]
I first "purchased" the extension from marketplace (v. 1.0.27) but I couln't install it due to compatibility issue.
Then I came her to github where I found the version (1.23) that is compatible with Magento 2.2.2 so could install it with composer.
The problem is now that Extension manager is stuck and complaining about not been able to execute git clone (see below):
Command "show" failed: [RuntimeException] Failed to execute git clone --mirror 'git@github.com:EaDesgin/magento2-pdf-generator2.git' '/usr/local/var/www/Magento/var/composer_home/cache/vcs/git-github.com-EaDesgin-magento2-pdf-generator2.git/' show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>] 
Seems like some kind of sync conflict between installed version through composer and the one I purchased in marketplace.
Marketplace dosn't have any option of removing purchased items so I'm kind of stuck here too :(
I've just reported the issue to the market place but I thought you might want to know and possibly have a solution for this.

**Comment by eadesignro** [comment]
Hi,
@neskoc The marketplace issue is not related to our product. And is also known to generate issues. I think this is why there is a professional installation service added. If you delete/remove the extension form the var folder and/or db the issue should go away. Be careful this is my best guess and i did not test this.

**Comment by neskoc** [comment]
Roll back of the previous backup solved the issue.
The error appeared on the other computer with some other magento installation (2.2.2) though complaining on some other extension (I didn't even have pdf-generator installed there) so you are right it was not related to this extension (nor magento installation - I claimed wrongly it was 2.2.2 though it was 2.2.1).
After some googling and experimenting I could narrow it down to the problem with git/ssh connection. I'm not really sure why/when it started and whether it is related to some other extension I installed with composer or some change in marketplace. Anyhow f.y.i. generating ssh-keys and uploading the public one in my github profile solved the issue.
For reference this: https://gist.github.com/adamjohnson/5682757 got me on right track :)

p.s. Do you have any advice about how (if possible) to add an image (logo) in the template? In your video I've seen some much more advanced templates with images (obviously not the same version of the extension). Even a built in invoice template allows to some degree adding logo.

p.p.s. I just started learning Magento, why would I need professional installation service for that? ;)
