### ISSUE TITLE
Filtering template error

### ISSUE THREAD

**Issue by kerlama** [EaDesgin/magento2-pdf-generator2#38]
Hi,

I am using your extension on few websites and it is very good. I just found issue with this line in template:

 {{var order.payment.method_instance.title}}

when this line is in template, I am getting template filter error, so I had to change the code in Helper/Pdf.php in _transport function:

I added this:

$paymentTitle= $order->getPayment()->getMethodInstance()->getTitle();
and then in transport array I added:

'paymentInfo' => $paymentTitle

Then in template I used this:
{{var paymentInfo|raw}}

With this implementation I am getting correct payment method.

Thanks

**Comment by catalineadesign** [comment]
Hi, was added this implementation. Thank you for the suggestion!
