### ISSUE TITLE
2.2.2 Error

### ISSUE THREAD

**Issue by dmg17** [EaDesgin/magento2-pdf-generator2#39]
Hi,

We were installing this extension on 2,2,2 and had an error when command 'setip:di:compile'
Here's how to fix:
diff --git a/app/code/Eadesigndev/Pdfgenerator/Model/ResourceModel/Pdfgenerator/Grid/Collection.php
b/app/code/Eadesigndev/Pdfgenerator/Model/ResourceModel/Pdfgenerator/Grid/Collection.php
index b7ddc1d..57aa4df 100644
--- a/app/code/Eadesigndev/Pdfgenerator/Model/ResourceModel/Pdfgenerator/Grid/Collection.php
+++ b/app/code/Eadesigndev/Pdfgenerator/Model/ResourceModel/Pdfgenerator/Grid/Collection.php
@@ -72,7 +72,7 @@ class Collection extends PdfCollection implements SearchResultInterface
$eventObject,
$resourceModel,
$model = 'Magento\Framework\View\Element\UiComponent\DataProvider\Document',
- $connection = null,
+ \Magento\Framework\DB\Adapter\AdapterInterface $connection = null,
AbstractDb $resource = null
) {
parent::__construct(

Can you help?

**Comment by catalineadesign** [comment]
I made a test on 2.2.2. and nothing wrong on di:compile.
