### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by Sylvesterx1** [EaDesgin/magento2-pdf-generator2#40]
Hi,
I am trying to install a pdf generator but I have an error (via composer):
Run command:
composer require eadesignro/module-pdfgenerator

then I generated the github token and typed.  I received the information that the token is correct and then the error:

  [RuntimeException]
  Failed to clone git@github.com:EaDesgin/magento2-pdf-generator2.git, git wa
  s not found, check that it is installed and in your PATH env.

  sh: git: command not found

anyone know how to solve it ?

**Comment by catalineadesign** [comment]
The install via composer working well. I can not reproduce your error.
