### ISSUE TITLE
SQLSTATE[42S02] error in Manage PDF Templates

### ISSUE THREAD

**Issue by miaosun** [EaDesgin/magento2-pdf-generator2#42]
Dear developers, 

I have followed the installation instruction (https://github.com/EaDesgin/magento2-pdf-generator2) and successfully installed the pdf generator extension in my Magento 2.2.2 website, the problem is when I go to "EADESIGN->Manage PDF Templates", it gives the following error: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tomavoxc_mobiparts.eadesign_pdf_templates' doesn't exist, query was: SELECT COUNT(*) FROM `eadesign_pdf_templates` AS `main_table`", can you please have a look why it is happening? Did I miss anythig?

**Comment by eadesignro** [comment]
@miaosun 

We did not encounter such issues. I recommend you reinstall the module.

**Comment by GuilhermeRava** [comment]
Hello @eadesignro, i found the same error too.
![error](https://user-images.githubusercontent.com/35239864/37840390-d62454ac-2eb4-11e8-8c72-961be3fed075.png)

I Tried reinstalling like you said, but it didnt work.
Do you have any solutions?
Thanks!

**Comment by miaosun** [comment]
@eadesignro , any update, please?
