### ISSUE TITLE
Arabic languages not working 

### ISSUE THREAD

**Issue by ahmadalkaid** [EaDesgin/magento2-pdf-generator2#43]
I had an issue with the Arabic languages on this extension, could you check the attached img: 

 
![download 44](https://user-images.githubusercontent.com/9692159/37274547-7c0c4c72-25e5-11e8-8fc9-d612a5908ccb.png)

**Comment by eadesignro** [comment]
To little info. It cannot be replicated.

**Comment by ahmadalkaid** [comment]
The issue in front of you, please have a look into the attached img. You can see that the product name are showing invalid characters. Which are coming from the product name in Arabic language.

Thanks,

**Comment by eadesignro** [comment]
@ahmadalkaid 
Our module offers support for multiple languages, RTL righting and so on. If you are not able to use it/ configure the module to his full potential hire a professional. Good luck!

**Comment by ahmadalkaid** [comment]
Hmmm, the issue here about the module it self. That when I print the invoice it seem that the order grid details not editable since you are calling the default variable. And after I edit the font to try it, it works fine with the text inside the eadesign template, but as I mention it's not working with the order gird items.
Also no need for me to hire a professional, since you are sharing EAdesign work with us :)

**Comment by Sumayah90** [comment]
@ahmadalkaid 
you can find the solution here
https://github.com/EaDesgin/magento2-pdf-generator2/issues/16

**Comment by Farkouh2000** [comment]
Hi,
still i cant find the solution  for this issue 
if anyone know how it is solved please help me with details 
thank you

**Comment by Sumayah90** [comment]
@Farkouh2000 
just add this code to Helper>PDF.php 
next to $pdf->SetHTMLHeader($parts['header']);

```
$pdf->SetDirectionality('rtl');
$pdf->autoScriptToLang = true;
$pdf->autoLangToFont = true;

```

**Comment by Farkouh2000** [comment]
@Sumayah90
hi 
thanks for replying
i cant find the file pdf.php anywhere in my magento site folders
i am using community version 2.3

**Comment by Farkouh2000** [comment]
@
hi 
It works .. the PDF is working perfectly thank you for your help
