### ISSUE TITLE
Feature request:  printing invoices by mass action

### ISSUE THREAD

**Issue by gewaechshaus** [EaDesgin/magento2-pdf-generator2#5]
Hey @eadesignro ,

what do you think about the idea to initialize the custom pdf also on the mass action "print invoices" in the admin order grid?

Regards
Jan

**Comment by eadesignro** [comment]
Hi @gewaechshaus 

Yes i am sure it wold. Is a bit more tricky to do that. Also that is available in the larger versions. We will think about that.

**Comment by gewaechshaus** [comment]
Hi @eadesignro 
thanks a lot... I will also take a look at the larger versions.

**Comment by gwharton** [comment]
Second vote for this feature to be available in this version.
