### ISSUE TITLE
Template not used for invoices

### ISSUE THREAD

**Issue by MarcusWolschon** [EaDesgin/magento2-pdf-generator2#53]
The plugin is installed (version "^1.2").
```
composer config repositories.magento2-pdf-generator2 git git@github.com:EaDesgin/magento2-pdf-generator2.git
composer require eadesignro/module-pdfgenerator --no-update"
```
The plugin is activated.
Stores->Configuration->EADesign Settings->Invoice PDF Generator shows the plugin as active.
Stores->Configuration->Advanced->Advanced the plugins "Eadesigndev_Eacore" and "Eadesigndev_Pdfgenerator" are enabled.

A template " Invoice Template Portrait!" exists,
is enabled, 
is the default template,
is the template for the store view "German" (also tried "English")

I watched the 18 minute video twice (in low resolution because of limited bandwidth) and could not find anything mentioned that I missed.

...still in a newly created order the action "Print Invoices" and "Print" show up PDF files created from the default magento invoice system instead of the mentioned template.

**Comment by MarcusWolschon** [comment]
Found it myself.
Do NOT select a dozen orders and use Action"PDF Invoices" but 
enter EACH individual order and select "print".

So this plugin only replaces one of the 2 print operations.
Sadly there is no "Print" action for MULTIPLE orders.

**Comment by florinlavric13** [comment]
I tested this extension for Magento 2.2.5, and works.
This extension, does not have implemented, option "print  invoices" from Action. For a printed invoice, use print from invoice view.

**Comment by MarcusWolschon** [comment]
So how to print the invoices for 40+ selected orders?
