### ISSUE TITLE
Feature Request - print multiple invoices at once

### ISSUE THREAD

**Issue by MarcusWolschon** [EaDesgin/magento2-pdf-generator2#56]
The current implementation can only print single invoices.
For 40+ invoices you need to navigate into every single order and print the invoices individually.

The default invoice module of magenta as well as postage printing can print via a mass action for a number of selected orders at once. This extension should not be worse then the default module.

**Comment by alexgillon** [comment]
I agree, I need the ability to be able to print multiple invoices at once, but this extension only works on the order page. When I try and print multiple invoices at once from the order grid, Magento uses the default PDF template.

Is it possible for this extension to work from the order grid too?

**Comment by MarcusWolschon** [comment]
**Note:**
I personally no longer have need for this. (The feature request remains valid.)
I stopped using this plugin and took the time to write my own with barcodes and everything.

**Comment by eadesignro** [comment]
We have added the feature request to our internal issues system. 
Thanks for the suggestions.

**Comment by alexgillon** [comment]
Great news, have you got any kind of ETA for this feature?
