### ISSUE TITLE
Admin Language Setting is used for Invoice generation

### ISSUE THREAD

**Issue by arendtio** [EaDesgin/magento2-pdf-generator2#57]
I set up a new shop and configured it to have a German store. For my admin user, I kept the English language as it makes it much easier to search for help when you have a problem.

After I installed magento2-pdf-generator2, I wondered why I had the English number (and date) format in the invoices while everything else in the shop has the German number format. Even the order confirmation email had the German number format. At first, I thought the extension doesn't support other number formats, but then I tried to change the language of my admin user et voilá: everything looked fine.

In my opinion, this is a bug, and the invoice generator should use the same language setting as the email generator (probably the store locale).

**Versions**
Magento: 2.1.11
PDF-Generator2: 1.2.3

PS, thank you for sharing this great extension with us.

**Comment by eadesignro** [comment]
We will not move this to a new feature. Thanks for the suggestion.
