### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by gewaechshaus** [EaDesgin/magento2-pdf-generator2#6]
Total Errors Count: 1
     Errors during compilation:
     Eadesigndev\Pdfgenerator\Controller\Adminhtml\Templates\Edit 
     Incorrect dependency in class Eadesigndev\Pdfgenerator\Controller\Adminhtml\Templates\Edit 
     in /var/www/html/vendor/eadesignro/module-pdfgenerator/Controller/Adminhtml/Templates/Edit.php
     \Magento\Backend\Model\Session already exists in context object

**Comment by gewaechshaus** [comment]
And even after running 

    setup:upgrade 

There has been an error processing your request

Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Eadesigndev_Eacore schema: current version - 0.0.5, required version - 0.0.4
Eadesigndev_Eacore data: current version - 0.0.5, required version - 0.0.4

**Comment by eadesignro** [comment]
@gewaechshaus 

Hi,

This is solved on. You can use the master branch until a new release is published.

**Comment by gewaechshaus** [comment]
@eadesignro - Hi Lucian,
are you refering https://github.com/EaDesgin/magento2-pdf-generator2/commit/4e14f6678b0f0f321066055bbf544789042cb047 ? Just to understand you right...

**Comment by eadesignro** [comment]
@gewaechshaus 

yes, that is that one.
