### ISSUE TITLE
addAttachment does not work with Magento 2.3

### ISSUE THREAD

**Issue by nobodyMO** [EaDesgin/magento2-pdf-generator2#72]

**Comment by nobodyMO** [comment]
The implementation of this functionality for Magento 2.3.x is different from that of previous versions. The reason is that in most cases the 2.3.x framework uses Zend Framework 2 (ZF2) and almost totally refuses to apply ZF1. createAttachment() is no longer a method of the message object. 
I cant't send any invoice mail with Magento 2.3 (and zend mail 2.x).

**Comment by eadesignro** [comment]
@nobodyMO 

The problem is solved.
