### ISSUE TITLE
Transactional Emails are empty

### ISSUE THREAD

**Issue by mjamb** [EaDesgin/magento2-pdf-generator2#74]
Hi EADesign-Team,
the Transactional emails are empty with attached pdf. When I switch the extension off, the mails contain their content / layout . Any help would be appreciated.

Magento 2.3

Disabled Modules:
Magento_Analytics // Amazon_Core
Magento_Inventory // Magento_InventoryAdminUi
Magento_InventoryApi // Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi // Magento_InventoryCatalog
Magento_InventorySales // Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi // Magento_InventoryCatalogSearch // Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi // Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration // Magento_InventoryConfigurationApi
Magento_InventoryGroupedProduct // Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer // Magento_InventoryImportExport
Magento_InventoryIndexer // Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationAdminUi // Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi // Magento_InventoryProductAlert
Magento_InventoryReservations // Magento_InventoryReservationsApi
Magento_InventoryCache // Magento_InventorySalesAdminUi
Magento_InventorySalesApi // Magento_InventorySalesFrontendUi
Magento_InventoryShipping // Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection // Magento_InventorySourceSelectionApi
Magento_NewRelicReporting // Magento_Braintree
Klarna_Core // Amazon_Login // Amazon_Payment // Magento_InventoryShippingAdminUi
Magento_Signifyd // Klarna_Ordermanagement // Klarna_Kp // Magento_Weee
Dotdigitalgroup_Email // Temando_Shipping // Vertex_Tax //

**Comment by gamort** [comment]
I suspect the problem is https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Email/SenderBuilder.php

The constructor was changed to deal with multi-store mode so https://github.com/EaDesgin/magento2-pdf-generator2/blob/master/Model/Email/SenderBuilder.php needs to be updated

Note: this will also affect later versions of 2.2 since the change was backported  https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sales/Model/Order/Email/SenderBuilder.php

**Comment by gabriela89** [comment]
On the magento 2.3 standard everything work well.

**Comment by patchee500** [comment]
We also got empty emails after upgrading to Magento 2.3 (not sure if that was the cause tbh).  
This was our fix: https://github.com/idowapro/magento2-pdf-generator2/commit/b4c7e2dc3f72ddf08889838ddf3b8f78c82800c8
