### ISSUE TITLE
Upgrade to Proforma Invoice PDF Generator fails

### ISSUE THREAD

**Issue by gamort** [EaDesgin/magento2-pdf-generator2#76]
We had to use an earlier version of this extension on Magento 2.2.6    Attempted to upgrade to "Proforma Invoice PDF Generator" after purchasing from the EAdesigns website and no version of that  extension works.    We have tried to reach you via both email addresses on your website, https://www.eadesign.ro/contact-us and have not received a reply.

**Comment by eadesignro** [comment]
I am sure someone is responding or will respond to you. We have a 24 hour maximum response time in working days. Thanks,
