### ISSUE TITLE
Fatel Error on module install.

### ISSUE THREAD

**Issue by devqualwebs** [EaDesgin/magento2-pdf-generator2#80]
Hello, 
I'm installing this module in my magento 2 website version 2.1.3
But after installing module, an error is showing in admin panel - "Access level to Eadesigndev\Pdfgenerator\Model\Email\Message::$messageType must be protected (as in class Magento\Framework\Mail\Message) or weaker in C:\xampp\htdocs\ladoun-test\app\code\Eadesigndev\Pdfgenerator\Model\Email\Message.php on line 16".

I also Tried to debug this, Looked on the same path. But not found any file named MessageInterface.php
inside "Magento\Framework\Mail". Can you please help me to find the solution?

**Comment by mardeleanu** [comment]
Hello,
Please tell me what is the version for Pdf Generator module and what php do you have installed.

**Comment by devqualwebs** [comment]
Php version is 7.0.4 and the extension version is 1.2.8.

**Comment by eadesignro** [comment]
The version 1.2.8 is not compatible with the php version 7.0.4. Please read composer documentation about versioning.
