### ISSUE TITLE
Arial font is default template css?

### ISSUE THREAD

**Issue by twocs** [EaDesgin/magento2-pdf-generator2#86]
The first line of the default css:
`@font-face {font-family: Arial;}`

However, mpdf [does not support an Arial font](https://mpdf.github.io/fonts-languages/available-fonts-v6.html). Additionally, there is no `src` in the font-face directive. It is a useless line as far as I can tell. Since it does nothing, I think you should delete this from your defaults.

Although the description of the EaDesign PDF Generator says it's easy to swap fonts with the invoices, there's no information about it in the guides, and there's no example in the css code. I'd suggest that you include font changing css in the default template. For reference, a css class should take the font in css like this: 
`div {font-family: sans;}`

Finally, it might be helpful to mention that many types of css do not work with mpdf. For example this will not apply font-family to any elements.
`* { font-family: sans; }`

**Comment by eadesignro** [comment]
The font needs to be added as needed in the mpdf/extension documentation.

**Comment by twocs** [comment]
In my experience, you cannot simply add a font as documented by mpdf 7. https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

The font details should be defined in the fontdata configuration variable. The place we had to edit this plugin to enable this basic functionality is inside a private method, near this line:

`$pdf = $this->mpdfFactory->create(['config' => $config]);` https://github.com/EaDesgin/magento2-pdf-generator2/blob/master/Helper/Pdf.php#L173

Correct me if I'm wrong, I don't pretend to be a pdf generation expert, but notice there's no fontdata configuration variable in this factory method? In my opinion it is very easy to add this functionality, but to do so breaks the architecture. Either we're bypassing private config methods or we're swapping out one mpdf object for another--bad code smells either way.

Other than that, the plugin works quite well.
