### ISSUE TITLE
Unable to Save Some Category in Magento2

### ISSUE THREAD

**Issue by abhishek1991-mag** [EaDesgin/magento2-pdf-generator2#88]
When I am trying to save some category then getting this error and category is not being saved..
For example we are trying to save Anchor to Yes/No.

****Warning: ltrim() expects parameter 1 to be string, array given in /var/www/html/eoutlet/public_html/app/code/Magento/Catalog/Model/Category/FileInfo.php on line 102****

My Magento Version : 2.2.5
If anyone also faced this issues, then please revert me?

Thanks

**Comment by zeshanrahman** [comment]
i am facing same issue can anyone help me
