### ISSUE TITLE
Incompatibility with Magento 2.3.4

### ISSUE THREAD

**Issue by Mo3ta9em93** [EaDesgin/magento2-pdf-generator2#93]
`PHP Fatal error:  Access level to Eadesigndev\Pdfgenerator\Model\Email\Message::$zendMessage must be protected (as in class Magento\Framework\Mail\Message) or weaker in /app/code/Eadesigndev/Pdfgenerator/Model/Email/Message.php on line 17`

error after updating to Magento 2.3.4

**Comment by Adimonta** [comment]
Change in /vendor/eadesignro/module-pdfgenerator/Model/Email/Message.php the "private $zendMessage;" to "protected $zendMessage;"
